package  com.ird.faa;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import java.util.*;
import java.util.stream.Stream;

import com.ird.faa.security.common.AuthoritiesConstants;
import com.ird.faa.security.bean.User;
import com.ird.faa.security.bean.Permission;
import com.ird.faa.security.bean.Role;
import com.ird.faa.security.service.facade.UserService;
import com.ird.faa.security.service.facade.RoleService;
import com.ird.faa.bean.Chercheur;


@SpringBootApplication
public class FaaApplication {
public static ConfigurableApplicationContext ctx;

public static void main(String[] args) {
ctx=SpringApplication.run(FaaApplication.class, args);
}

public static ConfigurableApplicationContext getCtx() {
return ctx;
}

@Bean
public CommandLineRunner demo(UserService userService, RoleService roleService
) {
return (args) -> {
if(false){
    Map<String,String> etats=new HashMap<>();
    etats.put("Initialisé","initialise");
    etats.put("En cours","encours");
    etats.put("Terminé","termine");


    // Role chercheur
        Chercheur userForChercheur = new Chercheur("chercheur");

    Role roleForChercheur = new Role();
    roleForChercheur.setAuthority(AuthoritiesConstants.CHERCHEUR);
    List<Permission> permissionsForChercheur = new ArrayList<>();
    addPermissionForChercheur(permissionsForChercheur);
    roleForChercheur.setPermissions(permissionsForChercheur);
    if(userForChercheur.getRoles()==null)
    userForChercheur.setRoles(new ArrayList<>());

    userForChercheur.getRoles().add(roleForChercheur);
    userService.save(userForChercheur);


    // Role admin
        User userForAdmin = new User("admin");

    Role roleForAdmin = new Role();
    roleForAdmin.setAuthority(AuthoritiesConstants.ADMIN);
    List<Permission> permissionsForAdmin = new ArrayList<>();
    addPermissionForAdmin(permissionsForAdmin);
    roleForAdmin.setPermissions(permissionsForAdmin);
    if(userForAdmin.getRoles()==null)
    userForAdmin.setRoles(new ArrayList<>());

    userForAdmin.getRoles().add(roleForAdmin);
    userService.save(userForAdmin);


    // Role client
        User userForClient = new User("client");

    Role roleForClient = new Role();
    roleForClient.setAuthority(AuthoritiesConstants.CLIENT);
    List<Permission> permissionsForClient = new ArrayList<>();
    addPermissionForClient(permissionsForClient);
    roleForClient.setPermissions(permissionsForClient);
    if(userForClient.getRoles()==null)
    userForClient.setRoles(new ArrayList<>());

    userForClient.getRoles().add(roleForClient);
    userService.save(userForClient);


    // Role contributeur
        User userForContributeur = new User("contributeur");

    Role roleForContributeur = new Role();
    roleForContributeur.setAuthority(AuthoritiesConstants.CONTRIBUTEUR);
    List<Permission> permissionsForContributeur = new ArrayList<>();
    addPermissionForContributeur(permissionsForContributeur);
    roleForContributeur.setPermissions(permissionsForContributeur);
    if(userForContributeur.getRoles()==null)
    userForContributeur.setRoles(new ArrayList<>());

    userForContributeur.getRoles().add(roleForContributeur);
    userService.save(userForContributeur);
    }
        };
        }

        private static void addPermissionForChercheur(List
        <Permission> permissions){
                permissions.add(new Permission("TypePaiement.edit"));
                permissions.add(new Permission("TypePaiement.list"));
                permissions.add(new Permission("TypePaiement.view"));
                permissions.add(new Permission("TypePaiement.add"));
                permissions.add(new Permission("TypePaiement.delete"));
                permissions.add(new Permission("EtatAbonnement.edit"));
                permissions.add(new Permission("EtatAbonnement.list"));
                permissions.add(new Permission("EtatAbonnement.view"));
                permissions.add(new Permission("EtatAbonnement.add"));
                permissions.add(new Permission("EtatAbonnement.delete"));
                permissions.add(new Permission("Contract.edit"));
                permissions.add(new Permission("Contract.list"));
                permissions.add(new Permission("Contract.view"));
                permissions.add(new Permission("Contract.add"));
                permissions.add(new Permission("Contract.delete"));
                permissions.add(new Permission("Signature.edit"));
                permissions.add(new Permission("Signature.list"));
                permissions.add(new Permission("Signature.view"));
                permissions.add(new Permission("Signature.add"));
                permissions.add(new Permission("Signature.delete"));
                permissions.add(new Permission("TypeContrat.edit"));
                permissions.add(new Permission("TypeContrat.list"));
                permissions.add(new Permission("TypeContrat.view"));
                permissions.add(new Permission("TypeContrat.add"));
                permissions.add(new Permission("TypeContrat.delete"));
                permissions.add(new Permission("PanierItem.edit"));
                permissions.add(new Permission("PanierItem.list"));
                permissions.add(new Permission("PanierItem.view"));
                permissions.add(new Permission("PanierItem.add"));
                permissions.add(new Permission("PanierItem.delete"));
                permissions.add(new Permission("CategorieImage.edit"));
                permissions.add(new Permission("CategorieImage.list"));
                permissions.add(new Permission("CategorieImage.view"));
                permissions.add(new Permission("CategorieImage.add"));
                permissions.add(new Permission("CategorieImage.delete"));
                permissions.add(new Permission("Panier.edit"));
                permissions.add(new Permission("Panier.list"));
                permissions.add(new Permission("Panier.view"));
                permissions.add(new Permission("Panier.add"));
                permissions.add(new Permission("Panier.delete"));
                permissions.add(new Permission("Chercheur.edit"));
                permissions.add(new Permission("Chercheur.list"));
                permissions.add(new Permission("Chercheur.view"));
                permissions.add(new Permission("Chercheur.add"));
                permissions.add(new Permission("Chercheur.delete"));
                permissions.add(new Permission("OffreReduction.edit"));
                permissions.add(new Permission("OffreReduction.list"));
                permissions.add(new Permission("OffreReduction.view"));
                permissions.add(new Permission("OffreReduction.add"));
                permissions.add(new Permission("OffreReduction.delete"));
                permissions.add(new Permission("TypeContributeur.edit"));
                permissions.add(new Permission("TypeContributeur.list"));
                permissions.add(new Permission("TypeContributeur.view"));
                permissions.add(new Permission("TypeContributeur.add"));
                permissions.add(new Permission("TypeContributeur.delete"));
                permissions.add(new Permission("EtatPanier.edit"));
                permissions.add(new Permission("EtatPanier.list"));
                permissions.add(new Permission("EtatPanier.view"));
                permissions.add(new Permission("EtatPanier.add"));
                permissions.add(new Permission("EtatPanier.delete"));
                permissions.add(new Permission("EtatImage.edit"));
                permissions.add(new Permission("EtatImage.list"));
                permissions.add(new Permission("EtatImage.view"));
                permissions.add(new Permission("EtatImage.add"));
                permissions.add(new Permission("EtatImage.delete"));
                permissions.add(new Permission("Client.edit"));
                permissions.add(new Permission("Client.list"));
                permissions.add(new Permission("Client.view"));
                permissions.add(new Permission("Client.add"));
                permissions.add(new Permission("Client.delete"));
                permissions.add(new Permission("TagBucket.edit"));
                permissions.add(new Permission("TagBucket.list"));
                permissions.add(new Permission("TagBucket.view"));
                permissions.add(new Permission("TagBucket.add"));
                permissions.add(new Permission("TagBucket.delete"));
                permissions.add(new Permission("StateBucket.edit"));
                permissions.add(new Permission("StateBucket.list"));
                permissions.add(new Permission("StateBucket.view"));
                permissions.add(new Permission("StateBucket.add"));
                permissions.add(new Permission("StateBucket.delete"));
                permissions.add(new Permission("TypeImage.edit"));
                permissions.add(new Permission("TypeImage.list"));
                permissions.add(new Permission("TypeImage.view"));
                permissions.add(new Permission("TypeImage.add"));
                permissions.add(new Permission("TypeImage.delete"));
                permissions.add(new Permission("Bucket.edit"));
                permissions.add(new Permission("Bucket.list"));
                permissions.add(new Permission("Bucket.view"));
                permissions.add(new Permission("Bucket.add"));
                permissions.add(new Permission("Bucket.delete"));
                permissions.add(new Permission("Abonnement.edit"));
                permissions.add(new Permission("Abonnement.list"));
                permissions.add(new Permission("Abonnement.view"));
                permissions.add(new Permission("Abonnement.add"));
                permissions.add(new Permission("Abonnement.delete"));
                permissions.add(new Permission("Tag.edit"));
                permissions.add(new Permission("Tag.list"));
                permissions.add(new Permission("Tag.view"));
                permissions.add(new Permission("Tag.add"));
                permissions.add(new Permission("Tag.delete"));
                permissions.add(new Permission("CategorieItem.edit"));
                permissions.add(new Permission("CategorieItem.list"));
                permissions.add(new Permission("CategorieItem.view"));
                permissions.add(new Permission("CategorieItem.add"));
                permissions.add(new Permission("CategorieItem.delete"));
                permissions.add(new Permission("Image.edit"));
                permissions.add(new Permission("Image.list"));
                permissions.add(new Permission("Image.view"));
                permissions.add(new Permission("Image.add"));
                permissions.add(new Permission("Image.delete"));
                permissions.add(new Permission("Paiement.edit"));
                permissions.add(new Permission("Paiement.list"));
                permissions.add(new Permission("Paiement.view"));
                permissions.add(new Permission("Paiement.add"));
                permissions.add(new Permission("Paiement.delete"));
                permissions.add(new Permission("PackAbonnement.edit"));
                permissions.add(new Permission("PackAbonnement.list"));
                permissions.add(new Permission("PackAbonnement.view"));
                permissions.add(new Permission("PackAbonnement.add"));
                permissions.add(new Permission("PackAbonnement.delete"));
                permissions.add(new Permission("TypeClient.edit"));
                permissions.add(new Permission("TypeClient.list"));
                permissions.add(new Permission("TypeClient.view"));
                permissions.add(new Permission("TypeClient.add"));
                permissions.add(new Permission("TypeClient.delete"));
                permissions.add(new Permission("Contributeur.edit"));
                permissions.add(new Permission("Contributeur.list"));
                permissions.add(new Permission("Contributeur.view"));
                permissions.add(new Permission("Contributeur.add"));
                permissions.add(new Permission("Contributeur.delete"));
            }
        private static void addPermissionForAdmin(List
        <Permission> permissions){
                permissions.add(new Permission("TypePaiement.edit"));
                permissions.add(new Permission("TypePaiement.list"));
                permissions.add(new Permission("TypePaiement.view"));
                permissions.add(new Permission("TypePaiement.add"));
                permissions.add(new Permission("TypePaiement.delete"));
                permissions.add(new Permission("EtatAbonnement.edit"));
                permissions.add(new Permission("EtatAbonnement.list"));
                permissions.add(new Permission("EtatAbonnement.view"));
                permissions.add(new Permission("EtatAbonnement.add"));
                permissions.add(new Permission("EtatAbonnement.delete"));
                permissions.add(new Permission("Contract.edit"));
                permissions.add(new Permission("Contract.list"));
                permissions.add(new Permission("Contract.view"));
                permissions.add(new Permission("Contract.add"));
                permissions.add(new Permission("Contract.delete"));
                permissions.add(new Permission("Signature.edit"));
                permissions.add(new Permission("Signature.list"));
                permissions.add(new Permission("Signature.view"));
                permissions.add(new Permission("Signature.add"));
                permissions.add(new Permission("Signature.delete"));
                permissions.add(new Permission("TypeContrat.edit"));
                permissions.add(new Permission("TypeContrat.list"));
                permissions.add(new Permission("TypeContrat.view"));
                permissions.add(new Permission("TypeContrat.add"));
                permissions.add(new Permission("TypeContrat.delete"));
                permissions.add(new Permission("PanierItem.edit"));
                permissions.add(new Permission("PanierItem.list"));
                permissions.add(new Permission("PanierItem.view"));
                permissions.add(new Permission("PanierItem.add"));
                permissions.add(new Permission("PanierItem.delete"));
                permissions.add(new Permission("CategorieImage.edit"));
                permissions.add(new Permission("CategorieImage.list"));
                permissions.add(new Permission("CategorieImage.view"));
                permissions.add(new Permission("CategorieImage.add"));
                permissions.add(new Permission("CategorieImage.delete"));
                permissions.add(new Permission("Panier.edit"));
                permissions.add(new Permission("Panier.list"));
                permissions.add(new Permission("Panier.view"));
                permissions.add(new Permission("Panier.add"));
                permissions.add(new Permission("Panier.delete"));
                permissions.add(new Permission("Chercheur.edit"));
                permissions.add(new Permission("Chercheur.list"));
                permissions.add(new Permission("Chercheur.view"));
                permissions.add(new Permission("Chercheur.add"));
                permissions.add(new Permission("Chercheur.delete"));
                permissions.add(new Permission("OffreReduction.edit"));
                permissions.add(new Permission("OffreReduction.list"));
                permissions.add(new Permission("OffreReduction.view"));
                permissions.add(new Permission("OffreReduction.add"));
                permissions.add(new Permission("OffreReduction.delete"));
                permissions.add(new Permission("TypeContributeur.edit"));
                permissions.add(new Permission("TypeContributeur.list"));
                permissions.add(new Permission("TypeContributeur.view"));
                permissions.add(new Permission("TypeContributeur.add"));
                permissions.add(new Permission("TypeContributeur.delete"));
                permissions.add(new Permission("EtatPanier.edit"));
                permissions.add(new Permission("EtatPanier.list"));
                permissions.add(new Permission("EtatPanier.view"));
                permissions.add(new Permission("EtatPanier.add"));
                permissions.add(new Permission("EtatPanier.delete"));
                permissions.add(new Permission("EtatImage.edit"));
                permissions.add(new Permission("EtatImage.list"));
                permissions.add(new Permission("EtatImage.view"));
                permissions.add(new Permission("EtatImage.add"));
                permissions.add(new Permission("EtatImage.delete"));
                permissions.add(new Permission("Client.edit"));
                permissions.add(new Permission("Client.list"));
                permissions.add(new Permission("Client.view"));
                permissions.add(new Permission("Client.add"));
                permissions.add(new Permission("Client.delete"));
                permissions.add(new Permission("TagBucket.edit"));
                permissions.add(new Permission("TagBucket.list"));
                permissions.add(new Permission("TagBucket.view"));
                permissions.add(new Permission("TagBucket.add"));
                permissions.add(new Permission("TagBucket.delete"));
                permissions.add(new Permission("StateBucket.edit"));
                permissions.add(new Permission("StateBucket.list"));
                permissions.add(new Permission("StateBucket.view"));
                permissions.add(new Permission("StateBucket.add"));
                permissions.add(new Permission("StateBucket.delete"));
                permissions.add(new Permission("TypeImage.edit"));
                permissions.add(new Permission("TypeImage.list"));
                permissions.add(new Permission("TypeImage.view"));
                permissions.add(new Permission("TypeImage.add"));
                permissions.add(new Permission("TypeImage.delete"));
                permissions.add(new Permission("Bucket.edit"));
                permissions.add(new Permission("Bucket.list"));
                permissions.add(new Permission("Bucket.view"));
                permissions.add(new Permission("Bucket.add"));
                permissions.add(new Permission("Bucket.delete"));
                permissions.add(new Permission("Abonnement.edit"));
                permissions.add(new Permission("Abonnement.list"));
                permissions.add(new Permission("Abonnement.view"));
                permissions.add(new Permission("Abonnement.add"));
                permissions.add(new Permission("Abonnement.delete"));
                permissions.add(new Permission("Tag.edit"));
                permissions.add(new Permission("Tag.list"));
                permissions.add(new Permission("Tag.view"));
                permissions.add(new Permission("Tag.add"));
                permissions.add(new Permission("Tag.delete"));
                permissions.add(new Permission("CategorieItem.edit"));
                permissions.add(new Permission("CategorieItem.list"));
                permissions.add(new Permission("CategorieItem.view"));
                permissions.add(new Permission("CategorieItem.add"));
                permissions.add(new Permission("CategorieItem.delete"));
                permissions.add(new Permission("Image.edit"));
                permissions.add(new Permission("Image.list"));
                permissions.add(new Permission("Image.view"));
                permissions.add(new Permission("Image.add"));
                permissions.add(new Permission("Image.delete"));
                permissions.add(new Permission("Paiement.edit"));
                permissions.add(new Permission("Paiement.list"));
                permissions.add(new Permission("Paiement.view"));
                permissions.add(new Permission("Paiement.add"));
                permissions.add(new Permission("Paiement.delete"));
                permissions.add(new Permission("PackAbonnement.edit"));
                permissions.add(new Permission("PackAbonnement.list"));
                permissions.add(new Permission("PackAbonnement.view"));
                permissions.add(new Permission("PackAbonnement.add"));
                permissions.add(new Permission("PackAbonnement.delete"));
                permissions.add(new Permission("TypeClient.edit"));
                permissions.add(new Permission("TypeClient.list"));
                permissions.add(new Permission("TypeClient.view"));
                permissions.add(new Permission("TypeClient.add"));
                permissions.add(new Permission("TypeClient.delete"));
                permissions.add(new Permission("Contributeur.edit"));
                permissions.add(new Permission("Contributeur.list"));
                permissions.add(new Permission("Contributeur.view"));
                permissions.add(new Permission("Contributeur.add"));
                permissions.add(new Permission("Contributeur.delete"));
            }
        private static void addPermissionForClient(List
        <Permission> permissions){
                permissions.add(new Permission("TypePaiement.edit"));
                permissions.add(new Permission("TypePaiement.list"));
                permissions.add(new Permission("TypePaiement.view"));
                permissions.add(new Permission("TypePaiement.add"));
                permissions.add(new Permission("TypePaiement.delete"));
                permissions.add(new Permission("EtatAbonnement.edit"));
                permissions.add(new Permission("EtatAbonnement.list"));
                permissions.add(new Permission("EtatAbonnement.view"));
                permissions.add(new Permission("EtatAbonnement.add"));
                permissions.add(new Permission("EtatAbonnement.delete"));
                permissions.add(new Permission("Contract.edit"));
                permissions.add(new Permission("Contract.list"));
                permissions.add(new Permission("Contract.view"));
                permissions.add(new Permission("Contract.add"));
                permissions.add(new Permission("Contract.delete"));
                permissions.add(new Permission("Signature.edit"));
                permissions.add(new Permission("Signature.list"));
                permissions.add(new Permission("Signature.view"));
                permissions.add(new Permission("Signature.add"));
                permissions.add(new Permission("Signature.delete"));
                permissions.add(new Permission("TypeContrat.edit"));
                permissions.add(new Permission("TypeContrat.list"));
                permissions.add(new Permission("TypeContrat.view"));
                permissions.add(new Permission("TypeContrat.add"));
                permissions.add(new Permission("TypeContrat.delete"));
                permissions.add(new Permission("PanierItem.edit"));
                permissions.add(new Permission("PanierItem.list"));
                permissions.add(new Permission("PanierItem.view"));
                permissions.add(new Permission("PanierItem.add"));
                permissions.add(new Permission("PanierItem.delete"));
                permissions.add(new Permission("CategorieImage.edit"));
                permissions.add(new Permission("CategorieImage.list"));
                permissions.add(new Permission("CategorieImage.view"));
                permissions.add(new Permission("CategorieImage.add"));
                permissions.add(new Permission("CategorieImage.delete"));
                permissions.add(new Permission("Panier.edit"));
                permissions.add(new Permission("Panier.list"));
                permissions.add(new Permission("Panier.view"));
                permissions.add(new Permission("Panier.add"));
                permissions.add(new Permission("Panier.delete"));
                permissions.add(new Permission("Chercheur.edit"));
                permissions.add(new Permission("Chercheur.list"));
                permissions.add(new Permission("Chercheur.view"));
                permissions.add(new Permission("Chercheur.add"));
                permissions.add(new Permission("Chercheur.delete"));
                permissions.add(new Permission("OffreReduction.edit"));
                permissions.add(new Permission("OffreReduction.list"));
                permissions.add(new Permission("OffreReduction.view"));
                permissions.add(new Permission("OffreReduction.add"));
                permissions.add(new Permission("OffreReduction.delete"));
                permissions.add(new Permission("TypeContributeur.edit"));
                permissions.add(new Permission("TypeContributeur.list"));
                permissions.add(new Permission("TypeContributeur.view"));
                permissions.add(new Permission("TypeContributeur.add"));
                permissions.add(new Permission("TypeContributeur.delete"));
                permissions.add(new Permission("EtatPanier.edit"));
                permissions.add(new Permission("EtatPanier.list"));
                permissions.add(new Permission("EtatPanier.view"));
                permissions.add(new Permission("EtatPanier.add"));
                permissions.add(new Permission("EtatPanier.delete"));
                permissions.add(new Permission("EtatImage.edit"));
                permissions.add(new Permission("EtatImage.list"));
                permissions.add(new Permission("EtatImage.view"));
                permissions.add(new Permission("EtatImage.add"));
                permissions.add(new Permission("EtatImage.delete"));
                permissions.add(new Permission("Client.edit"));
                permissions.add(new Permission("Client.list"));
                permissions.add(new Permission("Client.view"));
                permissions.add(new Permission("Client.add"));
                permissions.add(new Permission("Client.delete"));
                permissions.add(new Permission("TagBucket.edit"));
                permissions.add(new Permission("TagBucket.list"));
                permissions.add(new Permission("TagBucket.view"));
                permissions.add(new Permission("TagBucket.add"));
                permissions.add(new Permission("TagBucket.delete"));
                permissions.add(new Permission("StateBucket.edit"));
                permissions.add(new Permission("StateBucket.list"));
                permissions.add(new Permission("StateBucket.view"));
                permissions.add(new Permission("StateBucket.add"));
                permissions.add(new Permission("StateBucket.delete"));
                permissions.add(new Permission("TypeImage.edit"));
                permissions.add(new Permission("TypeImage.list"));
                permissions.add(new Permission("TypeImage.view"));
                permissions.add(new Permission("TypeImage.add"));
                permissions.add(new Permission("TypeImage.delete"));
                permissions.add(new Permission("Bucket.edit"));
                permissions.add(new Permission("Bucket.list"));
                permissions.add(new Permission("Bucket.view"));
                permissions.add(new Permission("Bucket.add"));
                permissions.add(new Permission("Bucket.delete"));
                permissions.add(new Permission("Abonnement.edit"));
                permissions.add(new Permission("Abonnement.list"));
                permissions.add(new Permission("Abonnement.view"));
                permissions.add(new Permission("Abonnement.add"));
                permissions.add(new Permission("Abonnement.delete"));
                permissions.add(new Permission("Tag.edit"));
                permissions.add(new Permission("Tag.list"));
                permissions.add(new Permission("Tag.view"));
                permissions.add(new Permission("Tag.add"));
                permissions.add(new Permission("Tag.delete"));
                permissions.add(new Permission("CategorieItem.edit"));
                permissions.add(new Permission("CategorieItem.list"));
                permissions.add(new Permission("CategorieItem.view"));
                permissions.add(new Permission("CategorieItem.add"));
                permissions.add(new Permission("CategorieItem.delete"));
                permissions.add(new Permission("Image.edit"));
                permissions.add(new Permission("Image.list"));
                permissions.add(new Permission("Image.view"));
                permissions.add(new Permission("Image.add"));
                permissions.add(new Permission("Image.delete"));
                permissions.add(new Permission("Paiement.edit"));
                permissions.add(new Permission("Paiement.list"));
                permissions.add(new Permission("Paiement.view"));
                permissions.add(new Permission("Paiement.add"));
                permissions.add(new Permission("Paiement.delete"));
                permissions.add(new Permission("PackAbonnement.edit"));
                permissions.add(new Permission("PackAbonnement.list"));
                permissions.add(new Permission("PackAbonnement.view"));
                permissions.add(new Permission("PackAbonnement.add"));
                permissions.add(new Permission("PackAbonnement.delete"));
                permissions.add(new Permission("TypeClient.edit"));
                permissions.add(new Permission("TypeClient.list"));
                permissions.add(new Permission("TypeClient.view"));
                permissions.add(new Permission("TypeClient.add"));
                permissions.add(new Permission("TypeClient.delete"));
                permissions.add(new Permission("Contributeur.edit"));
                permissions.add(new Permission("Contributeur.list"));
                permissions.add(new Permission("Contributeur.view"));
                permissions.add(new Permission("Contributeur.add"));
                permissions.add(new Permission("Contributeur.delete"));
            }
        private static void addPermissionForContributeur(List
        <Permission> permissions){
                permissions.add(new Permission("TypePaiement.edit"));
                permissions.add(new Permission("TypePaiement.list"));
                permissions.add(new Permission("TypePaiement.view"));
                permissions.add(new Permission("TypePaiement.add"));
                permissions.add(new Permission("TypePaiement.delete"));
                permissions.add(new Permission("EtatAbonnement.edit"));
                permissions.add(new Permission("EtatAbonnement.list"));
                permissions.add(new Permission("EtatAbonnement.view"));
                permissions.add(new Permission("EtatAbonnement.add"));
                permissions.add(new Permission("EtatAbonnement.delete"));
                permissions.add(new Permission("Contract.edit"));
                permissions.add(new Permission("Contract.list"));
                permissions.add(new Permission("Contract.view"));
                permissions.add(new Permission("Contract.add"));
                permissions.add(new Permission("Contract.delete"));
                permissions.add(new Permission("Signature.edit"));
                permissions.add(new Permission("Signature.list"));
                permissions.add(new Permission("Signature.view"));
                permissions.add(new Permission("Signature.add"));
                permissions.add(new Permission("Signature.delete"));
                permissions.add(new Permission("TypeContrat.edit"));
                permissions.add(new Permission("TypeContrat.list"));
                permissions.add(new Permission("TypeContrat.view"));
                permissions.add(new Permission("TypeContrat.add"));
                permissions.add(new Permission("TypeContrat.delete"));
                permissions.add(new Permission("PanierItem.edit"));
                permissions.add(new Permission("PanierItem.list"));
                permissions.add(new Permission("PanierItem.view"));
                permissions.add(new Permission("PanierItem.add"));
                permissions.add(new Permission("PanierItem.delete"));
                permissions.add(new Permission("CategorieImage.edit"));
                permissions.add(new Permission("CategorieImage.list"));
                permissions.add(new Permission("CategorieImage.view"));
                permissions.add(new Permission("CategorieImage.add"));
                permissions.add(new Permission("CategorieImage.delete"));
                permissions.add(new Permission("Panier.edit"));
                permissions.add(new Permission("Panier.list"));
                permissions.add(new Permission("Panier.view"));
                permissions.add(new Permission("Panier.add"));
                permissions.add(new Permission("Panier.delete"));
                permissions.add(new Permission("Chercheur.edit"));
                permissions.add(new Permission("Chercheur.list"));
                permissions.add(new Permission("Chercheur.view"));
                permissions.add(new Permission("Chercheur.add"));
                permissions.add(new Permission("Chercheur.delete"));
                permissions.add(new Permission("OffreReduction.edit"));
                permissions.add(new Permission("OffreReduction.list"));
                permissions.add(new Permission("OffreReduction.view"));
                permissions.add(new Permission("OffreReduction.add"));
                permissions.add(new Permission("OffreReduction.delete"));
                permissions.add(new Permission("TypeContributeur.edit"));
                permissions.add(new Permission("TypeContributeur.list"));
                permissions.add(new Permission("TypeContributeur.view"));
                permissions.add(new Permission("TypeContributeur.add"));
                permissions.add(new Permission("TypeContributeur.delete"));
                permissions.add(new Permission("EtatPanier.edit"));
                permissions.add(new Permission("EtatPanier.list"));
                permissions.add(new Permission("EtatPanier.view"));
                permissions.add(new Permission("EtatPanier.add"));
                permissions.add(new Permission("EtatPanier.delete"));
                permissions.add(new Permission("EtatImage.edit"));
                permissions.add(new Permission("EtatImage.list"));
                permissions.add(new Permission("EtatImage.view"));
                permissions.add(new Permission("EtatImage.add"));
                permissions.add(new Permission("EtatImage.delete"));
                permissions.add(new Permission("Client.edit"));
                permissions.add(new Permission("Client.list"));
                permissions.add(new Permission("Client.view"));
                permissions.add(new Permission("Client.add"));
                permissions.add(new Permission("Client.delete"));
                permissions.add(new Permission("TagBucket.edit"));
                permissions.add(new Permission("TagBucket.list"));
                permissions.add(new Permission("TagBucket.view"));
                permissions.add(new Permission("TagBucket.add"));
                permissions.add(new Permission("TagBucket.delete"));
                permissions.add(new Permission("StateBucket.edit"));
                permissions.add(new Permission("StateBucket.list"));
                permissions.add(new Permission("StateBucket.view"));
                permissions.add(new Permission("StateBucket.add"));
                permissions.add(new Permission("StateBucket.delete"));
                permissions.add(new Permission("TypeImage.edit"));
                permissions.add(new Permission("TypeImage.list"));
                permissions.add(new Permission("TypeImage.view"));
                permissions.add(new Permission("TypeImage.add"));
                permissions.add(new Permission("TypeImage.delete"));
                permissions.add(new Permission("Bucket.edit"));
                permissions.add(new Permission("Bucket.list"));
                permissions.add(new Permission("Bucket.view"));
                permissions.add(new Permission("Bucket.add"));
                permissions.add(new Permission("Bucket.delete"));
                permissions.add(new Permission("Abonnement.edit"));
                permissions.add(new Permission("Abonnement.list"));
                permissions.add(new Permission("Abonnement.view"));
                permissions.add(new Permission("Abonnement.add"));
                permissions.add(new Permission("Abonnement.delete"));
                permissions.add(new Permission("Tag.edit"));
                permissions.add(new Permission("Tag.list"));
                permissions.add(new Permission("Tag.view"));
                permissions.add(new Permission("Tag.add"));
                permissions.add(new Permission("Tag.delete"));
                permissions.add(new Permission("CategorieItem.edit"));
                permissions.add(new Permission("CategorieItem.list"));
                permissions.add(new Permission("CategorieItem.view"));
                permissions.add(new Permission("CategorieItem.add"));
                permissions.add(new Permission("CategorieItem.delete"));
                permissions.add(new Permission("Image.edit"));
                permissions.add(new Permission("Image.list"));
                permissions.add(new Permission("Image.view"));
                permissions.add(new Permission("Image.add"));
                permissions.add(new Permission("Image.delete"));
                permissions.add(new Permission("Paiement.edit"));
                permissions.add(new Permission("Paiement.list"));
                permissions.add(new Permission("Paiement.view"));
                permissions.add(new Permission("Paiement.add"));
                permissions.add(new Permission("Paiement.delete"));
                permissions.add(new Permission("PackAbonnement.edit"));
                permissions.add(new Permission("PackAbonnement.list"));
                permissions.add(new Permission("PackAbonnement.view"));
                permissions.add(new Permission("PackAbonnement.add"));
                permissions.add(new Permission("PackAbonnement.delete"));
                permissions.add(new Permission("TypeClient.edit"));
                permissions.add(new Permission("TypeClient.list"));
                permissions.add(new Permission("TypeClient.view"));
                permissions.add(new Permission("TypeClient.add"));
                permissions.add(new Permission("TypeClient.delete"));
                permissions.add(new Permission("Contributeur.edit"));
                permissions.add(new Permission("Contributeur.list"));
                permissions.add(new Permission("Contributeur.view"));
                permissions.add(new Permission("Contributeur.add"));
                permissions.add(new Permission("Contributeur.delete"));
            }


            }


